#!/bin/sh

_readlink() {
    [ ! -h "$1" ] && echo "$1" || (local link="$(expr "$(command ls -ld -- "$1")" : '.*-> \(.*\)$')"
    cd $(dirname $1)
    myreadlink "$link" | sed "s|^\([^/].*\)\$|$(dirname $1)/\1|")
}

# "imports"
this=$(dirname $(_readlink $0))
. "$this/libs/arrays"

# returns pairs of cnonected ports (one line per port)
get_cons() {
    IFS=$'\n'
    set -f
    for line in $(jack_lsp -c); do
        case "$line" in
            "   "*) b=$(echo "$line" | cut -c 4-) ;;
            *) a="$line"; b='' ;;
        esac
        if [ ! -z $b ]; then
            echo "$a\n$b"
        fi

    done
}

disconnect_all() {
    a= ;b= ;c=0
    for line in $(get_cons); do
        if [ $(( $c % 2 )) = 0 ]; then
            a="$line"
        else
            b="$line"
            echo "disconnecting '$a' from '$b'"
            jack_disconnect "$a" "$b"
        fi
        c=$(( $c + 1 ))
    done
}

